// <auto-generated />
using System;
using Digi1Back.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Digi1Back.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Digi1Back.Models.Cliente", b =>
                {
                    b.Property<int>("cli_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cli_fecha_naci")
                        .HasColumnType("int");

                    b.Property<string>("cli_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cli_Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Digi1Back.Models.Factura", b =>
                {
                    b.Property<int>("fac_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fac_cantidad")
                        .HasColumnType("int");

                    b.Property<int>("fac_cli_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fac_fecha_compra")
                        .HasColumnType("datetime2");

                    b.Property<int>("fac_inv_Id")
                        .HasColumnType("int");

                    b.Property<int>("fac_pro_Id")
                        .HasColumnType("int");

                    b.Property<int>("fac_valor")
                        .HasColumnType("int");

                    b.HasKey("fac_Id");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Digi1Back.Models.Inventario", b =>
                {
                    b.Property<int>("inv_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("inv_cantidad")
                        .HasColumnType("int");

                    b.Property<int>("inv_pro_Id")
                        .HasColumnType("int");

                    b.HasKey("inv_Id");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("Digi1Back.Models.Producto", b =>
                {
                    b.Property<int>("pro_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("pro_medida")
                        .HasColumnType("int");

                    b.Property<string>("pro_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pro_precio")
                        .HasColumnType("int");

                    b.HasKey("pro_Id");

                    b.ToTable("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
